name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - name: Lint
        run: csbt scalafmtSbtCheck scalafmtCheckAll "scalafix --check"
      - name: Test
        run: csbt test scripted
